# Generated by Django 5.0.4 on 2024-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brmed', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.TextField(max_length=14),
        ),
    ]
